Allow CORS at SiteLevel
frappe/bench pull request #1013
Opened 2020-06-03 02:58 UTC by faztp12

What type of a PR is this?
- [x] New Feature Submissions
---

CORS can be a very helpful feature for sites hosted on static hosting providers. I would like to propose a config/flag to allow CORS on specific sites. By specifying `allow_cors: 1` either in the common site config / site config enables this.

TODO:
- Restricting CORS Origin to a specific set of domains instead of using wildcard (*) & optional `Allow Credentials`  
I will work on this if you guys feel CORS should be part of frappe/bench 😄 
- Tests  
- Updating Documentations  
Unfortunately I was unable to find docs related to wildcard_ssls or configs related to nginx in this repo, is it in frappe/frappe ?

2020-08-14 06:22 UTC, faztp12 commented
@adityahase I have update the PR, along with the description.
Do provide your thoughts on the direction this PR is headed 😄

2020-10-09 05:45 UTC, revant commented
For reference:

Alternative to programmatically set CORS headers, it works in dev bench.

https://discuss.erpnext.com/t/cors-on-localhost/60116/7

2020-10-30 04:01 UTC, adityahase requested changes
We're maintaing docs at https://github.com/frappe/frappe_docs/blob/master/frappe_docs/www/docs/user/en/bench/index.md.


Please include some tests.

2020-11-16 02:14 UTC, faztp12 commented on bench/config/nginx.py
> +	return parsed_config
Yep, let me check what can be done 👍

2020-11-16 02:16 UTC, faztp12 commented
@adityahase should we consider a python approach instead of modifying it in nginx ?
Something similar to what @revant mentioned ?

2020-12-28 09:31 UTC, faztp12 commented on bench/config/nginx.py
> +			return obj1 == obj2
@adityahase please check the updates..

2020-12-29 07:54 UTC, adityahase commented
@faztp12 Please add tests.

2020-12-29 07:55 UTC, faztp12 commented
@adityahase ok 👍

2021-01-09 11:33 UTC, revant commented
this got merged into framework.

https://github.com/frappe/frappe/pull/12183

2021-01-09 11:33 UTC, closed without merging