fix(install): Allow override of frappe_branch and erpnext_branch
frappe/bench pull request #1079
Opened 2020-10-03 09:13 UTC by ceefour

Allow override of frappe_branch and erpnext_branch
Regardless of args.version (which always has a default set).
Additionally, print useful log of (non-credentials) variables used.

What type of a PR is this?

- [ ] Changes to Existing Features
- [ ] New Feature Submissions
- [x] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

> Please provide enough information so that others can review your pull request:

Currently `--frappe-branch` and `--erpnext-branch` is always ignored because `--version` has a default (`12`).

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you lint your code locally prior to submission?
- [x] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

> Screenshots/GIFs

2020-10-28 07:19 UTC, gavindsouza requested changes

2020-10-28 07:19 UTC, gavindsouza commented on install.py
> +	log("Initializing bench using bench_name=%s frappe_branch=%s erpnext_branch=%s ..." % (bench_name, frappe_branch, erpnext_branch))
```suggestion
	log("Initializing bench {0}:\n\tFrappe Branch: {1}\n\tERPNext Branch: {2}".format(bench_name, frappe_branch, erpnext_branch))
```

Can we have something like this instead? Also, check if `--without-erpnext` or `--without-bench-setup` are passed and show the appropriate statement log here

2020-10-30 10:49 UTC, gavindsouza commented on install.py
> +	log("Initializing bench using bench_name=%s frappe_branch=%s erpnext_branch=%s ..." % (bench_name, frappe_branch, erpnext_branch))
>  Also, check if --without-erpnext or --without-bench-setup are passed and show the appropriate statement log here

Address this too ^

2020-10-30 10:54 UTC, ceefour commented
@gavindsouza Updated with more conditional and clearer logging.

2020-11-24 07:44 UTC, gavindsouza approved these changes

2020-11-24 07:44 UTC, merged