build(common_site_config): Change default worker count
frappe/bench pull request #1081
Opened 2020-10-03 11:56 UTC by ceefour

What type of a PR is this?

- [x] Changes to Existing Features
- [ ] New Feature Submissions
- [ ] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

> Please provide enough information so that others can review your pull request:

Fixes https://github.com/frappe/bench/issues/737 raised by @mr-karan.

Issue: Feature Request

Gunicorn official docs [suggest the number of workers to be 2*cores + 1](http://docs.gunicorn.org/en/stable/design.html#how-many-workers).

Can we change the default worker count from the number of cores to the above suggested number?

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [ ] Have you lint your code locally prior to submission?
- [ ] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

> Screenshots/GIFs

2020-10-27 13:05 UTC, gavindsouza requested changes

2020-10-27 13:05 UTC, gavindsouza commented on bench/config/common_site_config.py
> +		"gunicorn_workers": multiprocessing.cpu_count()*2 + 1
```suggestion
		"gunicorn_workers": multiprocessing.cpu_count() * 2 + 1
```

Fix styling and the commit message to follow semantic messages. refer https://www.conventionalcommits.org/en/v1.0.0/

2020-10-27 16:15 UTC, ceefour commented
@gavindsouza I've applied the suggestion including the commit message.

2020-10-28 06:19 UTC, gavindsouza approved these changes
Thank you for your contribution

2020-10-28 06:45 UTC, merged