refactor: bench init exits if error during "Installing frappe"
frappe/bench pull request #1083
Opened 2020-10-03 13:16 UTC by ceefour

Fixes https://github.com/frappe/bench/issues/1082

What type of a PR is this?

- [ ] Changes to Existing Features
- [ ] New Feature Submissions
- [x] Bug Fix
- [ ] Breaking Change (include change in API behaviours, etc.)

---

> Please provide enough information so that others can review your pull request:

Detect if command failed, then exit with status 1.

In `bench/app.py` `install_app()` -> `bench.utils.exec_cmd()`

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [ ] Have you lint your code locally prior to submission?
- [ ] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

> Screenshots/GIFs

2020-10-27 08:59 UTC, gavindsouza requested changes

2020-10-27 08:59 UTC, gavindsouza commented on bench/utils.py
> +  import shlex
```suggestion
	"""Executes cmd with cwd via subprocess.call and returns the process exit code"""
	import shlex
```

Give more info with lesser words. Fix indentation

2020-10-27 08:59 UTC, gavindsouza commented on bench/app.py
> +		pip=pip_path, quiet=quiet_flag, app=app_path, no_cache=cache_flag))
```suggestion
		pip_install_code = exec_cmd(
		"{pip} install {quiet} -U -e {app} {no_cache}".format(
			pip=pip_path, quiet=quiet_flag, app=app_path, no_cache=cache_flag
		)
	)
```
Styling fixes

2020-10-27 08:59 UTC, gavindsouza commented on bench/app.py
> +		sys.exit(pip_install_code)
Can you add a screenshot for this during execution?

2020-10-27 16:22 UTC, ceefour commented
@gavindsouza About screenshot, I documented a lot of the diagnosis process here: https://about.lovia.life/docs/infrastructure/erpnext/install-erpnext-on-ubuntu-vm/#Troubleshooting_3_psycopg2

So this was what happened:

![image](https://user-images.githubusercontent.com/24123/97330722-2be78700-18ab-11eb-9dfb-d88ab9399d27.png)

My patch stopped the execution if an error happened, since it doesn't make sense to continue....... which will throw another error anyway (with even more confusing error).

By stopping early, it's easier for user to figure out what went wrong, fix it, then they can retry.

2020-10-28 07:46 UTC, gavindsouza commented
@ceefour I get that part. I wasn't able to replicate failing dependency setups and I'd like to see how bench would exit with the proposed fix. Can you show me a replicable screenshot so that there are no unknowns before we go ahead with this change?

2020-10-28 15:27 UTC, ceefour commented
One way that happened to me is low disk space..

So to reproduce it:

1. Do not install any apps yet
2. Make it so the disk space is left only a bit (probably easier to do inside a Docker container) 
3. Do bench get-app erpnext.. When it fails installing frappe, you'll see it continue etc.
4. Compare behavior of above but with patch applied

2020-11-24 08:05 UTC, gavindsouza requested changes

2020-11-24 08:05 UTC, gavindsouza commented on bench/app.py
> +		pip_install_code = exec_cmd(
@ceefour Indentation error

2021-11-30 05:39 UTC, gavindsouza commented
Now, bench exits whenever any `exec_cmd` fails via https://github.com/gavindsouza/bench/commit/3995b9237b07ef5bef2fbd6a35000b7faa88ab2c. That should fix the issue this PR was addressing.

2021-11-30 05:39 UTC, closed without merging

2021-12-01 02:09 UTC, ceefour commented
Thank youuu @gavindsouza