fix(install): Obey --without-site
frappe/bench pull request #1087
Opened 2020-10-04 07:16 UTC by ceefour

What type of a PR is this?

- [x] Bug Fix

---

> Please provide enough information so that others can review your pull request:

Running `sudo python ./install.py --without-site` previously still created a site.

This fixes it and will skip creating a site if `--without-site` is specified.

---

> Explain the **details** for making this change. What existing problem does the pull request solve? The following checklist could help

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you lint your code locally prior to submission?
- [x] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?

---

> Screenshots/GIFs

2020-10-27 12:53 UTC, gavindsouza requested changes
We won't be needing administrator credentials too in case of `--without-site`. Can you remove the prompts for the same too?

![Screenshot 2020-10-27 at 6 22 34 PM](https://user-images.githubusercontent.com/36654812/97304287-88ce4780-1881-11eb-92d9-11690a712340.png)

2020-10-27 16:34 UTC, ceefour commented
@gavindsouza ok prompt now also dependent on `--without-site`

2020-10-28 07:11 UTC, gavindsouza approved these changes

2020-10-28 07:11 UTC, merged

2020-10-29 15:48 UTC, ceefour commented
BTW @gavindsouza, may I propose that frappe/frappe repository also tagged with #hacktoberfest ..?