fix(CLI): Traceback, Exit codes, logging management
frappe/bench pull request #1096
Opened 2020-10-30 15:24 UTC by gavindsouza

1. In case a command fails with an error, print the message and log the entire traceback in the bench log. 
1. If `--verbose` is a part of the bench command, print the traceback too
1. Pass down the appropriate exit code

Fixes https://github.com/frappe/bench/issues/1095

2021-01-25 18:46 UTC, barredterra requested changes

2021-01-25 18:46 UTC, barredterra commented on bench/__init__.py
> +	import traceback
Imports should be global

2021-01-25 18:46 UTC, barredterra commented on bench/cli.py
> +		if any([x for x in ["--verbose", "-v"] if x in sys.argv]):
```suggestion
		if any(x in sys.argv for x in ["--verbose", "-v"]):
```

2021-11-30 05:36 UTC, gavindsouza commented
This PR has been superseded by #1208

2021-11-30 05:36 UTC, closed without merging