fix: Replace certbot-auto with certbot
frappe/bench pull request #1152
Opened 2021-04-14 00:07 UTC by abhishekbalam

certbot-auto is depricated on many platforms. More information can be found [here](https://community.letsencrypt.org/t/certbot-auto-deprecated-explanation-and-solutions/139821)

This PR adds prerequisites for certbot and replaces all references to older commands.

Pls do not merge, testing is in progress.

2021-06-08 22:05 UTC, abhishekbalam commented
@revant @saurabh6790 

Removed setup scripts for certbot, it will be added in another PR later.

2021-06-14 09:53 UTC, abhishekbalam commented
Tested with @athul.

It works fine.

We need to update installation docs to ask users to install certbot seperately.

2021-07-19 08:20 UTC, gavindsouza requested changes
You can use f-strings instead for everything here.

2021-07-19 08:20 UTC, gavindsouza commented on bench/config/templates/frappe_sudoers
> +{{ user }} ALL = (root) NOPASSWD: /usr/bin/certbot
If certbot exists in bin, it exists in PATH. If that is true, you should use `bench.utils.which` instead. If nothing is found, you can pass this path into the template after verification.

2021-07-19 08:20 UTC, gavindsouza commented on bench/config/lets_encrypt.py
> -
Check if certbot is installed and prompt the user to install it following some ABCs. Perhaps a link to a guide on Frappe Docs

2021-07-19 08:20 UTC, gavindsouza commented on bench/config/lets_encrypt.py
> +from distutils.spawn import find_executable
Use `bench.utils.which` instead. We're trying to get rid of the distutils dependency.

2021-07-19 08:20 UTC, gavindsouza commented on bench/config/lets_encrypt.py
> +		exec_cmd("{path} certonly {interactive} -c /etc/letsencrypt/configs/{site}.cfg".format(path=get_certbot_path(), interactive=interactive, site=custom_domain or site))
Would be more readable as a f-string

2021-07-19 08:20 UTC, gavindsouza commented on bench/config/lets_encrypt.py
> +	job_command = '{path} renew --nginx -q --renew-hook "systemctl reload nginx"'.format(path=get_certbot_path())
Feel like this should check which service is being used, like `bench.utils.service` does

also, f-string

2021-08-17 06:13 UTC, gavindsouza commented
Any update on this? @abhishekbalam

2021-11-30 09:19 UTC, gavindsouza commented
Closing this due to inactivity (for ~7.5 months). Re-open when PR is ready.

2021-11-30 09:19 UTC, closed without merging